language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t itsmealves/docker-example-app -f Dockerfile.env .

script:
  - docker run -e CI=true itsmealves/docker-example-app npm run test